name: Cloud Credits Request
description: Submit a request for credits for a project
title: "Cloud Credits Request: "
labels: ["request"]
body:
  - type: input
    id: project
    attributes:
      label: Project
      description: Which CNCF project are credits needed for?
      placeholder: e.g. Kubernetes, Prometheus, Envoy...
    validations:
      required: true
  - type: input
    id: amount
    attributes:
      label: Amount
      description: Amount of credits needed
      placeholder: e.g. $50/month, $200/year, $5/week
    validations:
      required: true
  - type: input
    id: providers
    attributes:
      label: Providers
      description: The infrastructure provider to support the credits
      placeholder: e.g. AWS, Azure, GCP...
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional information
      description: Anything extra to note?
      placeholder: From the email...
    validations:
      required: true
